name: build-go
create:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Current Branch
      id: get-branch
      uses: codio/get-branch-name-github-action@v1

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

    - name: go get
      run: go get google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
      env:
        GO111MODULE: on

    - name: update PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Create binary path
      run: mkdir generated

    - name: generate interface
      run: find ./proto -type f -exec protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=generated --go-grpc_opt=paths=source_relative "{}" +
